name: main
on: [push]

jobs:
  # TODO: add some test jobs

  release:
    runs-on: ubuntu-22.04
    name: release
    # only release from the master branch
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - uses: bahmutov/npm-install@v1

      # https://github.com/cycjimmy/semantic-release-action
      - name: Semantic Release
        uses: cycjimmy/semantic-release-action@v3
        id: semantic
        with:
          branch: main
          dry_run: false
